openapi: '3.0.2'
info:
  title: API для лабораторных по микропроектированию
  version: '1.0'

tags:
  - name: Получение доступа к системе
    description: Методы получения доступа к системе
  - name: Выход из системы
    description: Метод выхода из системы
  - name: Восстановление пароля
    description: Методы восстановления пароля

paths:
  /sign-up:
    $ref: "paths/sign_up.yml"
  /log-in:
    $ref: "paths/log_in.yml"
  /log-out:
    $ref: "paths/log_out.yml"
  /send-letter:
    $ref: "paths/send_letter.yml"
  /check-token:
    $ref: "paths/check_token.yml"
  /change-password:
    $ref: "paths/change_password.yml"

components:
  securitySchemes:
    $ref: "security/jwt.yml"
